# Generated by Django 3.2.8 on 2022-09-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netprofit',
            old_name='netIncome',
            new_name='netProfitMargin',
        ),
        migrations.RemoveField(
            model_name='netprofit',
            name='revenue',
        ),
    ]
