# Generated by Django 3.2.8 on 2022-09-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalytics', '0002_auto_20220930_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netprofit',
            old_name='netProfitMargin',
            new_name='netIncome',
        ),
        migrations.AddField(
            model_name='netprofit',
            name='revenue',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
