# Generated by Django 3.2.8 on 2022-09-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalytics', '0003_auto_20220930_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
