# Generated by Django 3.2.8 on 2022-09-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalytics', '0004_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='netprofit',
            name='netProfit1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
