# Generated by Django 3.2.8 on 2022-09-30 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalytics', '0005_netprofit_netprofit1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netprofit',
            name='netProfit1',
        ),
    ]
