# Generated by Django 3.2.8 on 2022-10-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalytics', '0008_netprofitmargin'),
    ]

    operations = [
        migrations.AddField(
            model_name='netprofitmargin',
            name='profitMargin1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
